name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^7.6.7
  injectable: ^2.3.2
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  dio: ^5.4.0
  retrofit: ^4.5.0  # compatible with Dart <=3.5.x
  json_annotation: ^4.9.0
  logger: ^2.0.2
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3  # stay below v9 for Dart <=3.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  injectable_generator: ^2.2.0
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
